# Generated by Django 5.2 on 2025-04-15 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likeNcomment_system', '0002_comment_confession_like_delete_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'confession')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked_at',
        ),
    ]
