# Generated by Django 5.2 on 2025-05-04 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fullpost_system', '0006_reply_image_reply_is_gif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_key', models.CharField(max_length=40)),
                ('sender_key', models.CharField(max_length=40, null=True)),
                ('notification_type', models.CharField(choices=[('post_like', 'Post Liked'), ('comment_like', 'Comment Liked'), ('reply_like', 'Reply Liked'), ('post_comment', 'Post Commented'), ('comment_reply', 'Comment Replied')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fullpost_system.comment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fullpost_system.post')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fullpost_system.reply')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_key', 'is_read'], name='notificatio_recipie_53f12a_idx')],
            },
        ),
    ]
