# Generated by Django 5.2 on 2025-05-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar5.png', null=True, upload_to='avatars/'),
        ),
    ]
