# Generated by Django 5.2 on 2025-04-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
