# Generated by Django 5.2 on 2025-05-23 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0004_remove_report_post_remove_report_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='object_id',
        ),
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confession.comment'),
        ),
        migrations.AddField(
            model_name='report',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confession.post'),
        ),
    ]
