# Generated by Django 5.2 on 2025-05-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar5.png', null=True, upload_to='avatars/'),
        ),
    ]
