# Generated by Django 5.2 on 2025-06-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0008_notification_notification_type_notification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
