# Generated by Django 5.2 on 2025-06-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0010_notification_comment_notification_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report', 'Content Reported'), ('deleted', 'Content Deleted'), ('warning', 'Warning Issued'), ('ban', 'Account Banned'), ('post_liked', 'Post Liked'), ('comment_liked', 'Comment Liked'), ('reply_liked', 'Reply Liked'), ('commented', 'Commented'), ('replied', 'Replied')], default='report', max_length=20),
        ),
    ]
