# Generated by Django 5.2 on 2025-05-23 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0003_reply_user'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='post',
        ),
        migrations.RemoveField(
            model_name='report',
            name='session_key',
        ),
        migrations.AddField(
            model_name='report',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='report',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
