# Generated by Django 5.2 on 2025-05-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0005_remove_report_content_type_remove_report_object_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(name='Report'),
    ]
