# Generated by Django 5.2 on 2025-05-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0008_userprofile_bio_userprofile_display_name_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='avatar1.png', max_length=100),
        ),
    ]
