# Generated by Django 5.2 on 2025-05-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0011_remove_userprofile_display_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
