# Generated by Django 5.2 on 2025-05-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0012_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/avatar5.png', upload_to='avatars/'),
        ),
    ]
