# Generated by Django 5.2 on 2025-04-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullpost_system', '0002_reply_replylike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parent_comment',
        ),
    ]
