# Generated by Django 5.2 on 2025-04-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullpost_system', '0003_rename_parent_comment_parent_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment',
            new_name='parent',
        ),
    ]
