# Generated by Django 5.2 on 2025-05-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullpost_system', '0004_replyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_gif',
            field=models.BooleanField(default=False),
        ),
    ]
