# Generated by Django 5.2 on 2025-05-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullpost_system', '0005_comment_image_comment_is_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reply_images/'),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_gif',
            field=models.BooleanField(default=False),
        ),
    ]
