# Generated by Django 5.2 on 2025-05-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullpost_system', '0006_reply_image_reply_is_gif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreport',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='replyreport',
            name='session_key',
        ),
        migrations.AddField(
            model_name='commentreport',
            name='reporter_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='replyreport',
            name='reporter_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
