# Generated by Django 5.2 on 2025-05-08 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullpost_system', '0007_remove_commentreport_session_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_session_key', models.CharField(max_length=40)),
                ('sender_session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('notification_type', models.CharField(choices=[('post_like', 'Post Like'), ('comment_like', 'Comment Like'), ('reply_like', 'Reply Like'), ('new_comment', 'New Comment'), ('new_reply', 'New Reply')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fullpost_system.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fullpost_system.post')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fullpost_system.reply')),
            ],
        ),
    ]
