# Generated by Django 5.2 on 2025-05-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullpost_system', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='session_key',
            field=models.CharField(default='anonymous_default_key', max_length=40),
        ),
    ]
