# Generated by Django 5.2 on 2025-06-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0011_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report', 'Content Reported'), ('deleted', 'Content Deleted'), ('warning', 'Warning Issued'), ('ban', 'Account Banned'), ('post_like', 'Post Liked'), ('comment_like', 'Comment Liked'), ('reply_like', 'Reply Liked'), ('new_comment', 'New Comment'), ('new_reply', 'New Reply')], default='report', max_length=20),
        ),
    ]
